### ISSUE TITLE
Unifying links and actions

### ISSUE THREAD

**Issue by JornWildt** [JornWildt/Mason#11]
Would it be an idea to unify link, link-templates and actions into one single "links" element?

With this change I hope it becomes easier for client developers:

  1. Because the same link name/relation cannot exist in both links, templates and actions.
  1. It becomes easier to move from a simple "HAL-like" links-only representation to a representation with more meta data about the links (without breaking existing clients).
  1. Client behavior should be simplified (but that is mostly a gut feeling - no hard facts).

## Changes

  1. All links, templates and actions are now moved to @links.
  1. The "type" property now designates the type of link.
  1. The "target-type" property now designates target content type hint (this is the old "type" for links).
  1. The link "template" is now "href" (since "template" is used in the actions for a different purpose)

## Expected client behavior

  1. Assume having a (possibly empty) JSON data object for the operation (the payload or template variable set).
  1. Read resource, find @links.
  1. Find link by name.
  1. If link type is "link" then simply follow it with a GET and retry.
  1. If link is "link-template" then merge the "href" URL template with the JSON data object and follow the URL with a GET.
  1. If link is "json" and method is GET then form-url-encode the JSON data object, merge the result into the href URL and follow the URL with a GET.
  1. If link is "json" or "json+files" then merge data object with data template from the link description and send it to the server as either JSON or multipart (using the designated method).

### Simple link
Here we have a simple non-templated link

```
@links:
{
  "foo:a":
  {
    // "type" designates the type of link
    type: "link",
    href: "...",
    title: "...",
    // Old "type" (target content type hint) is now "target-type"
    target-type: ["text/vcard"],
    // "alt" is still alternative links (usually having different target types)
    alt: [ ... ]
  }
}
```

### Templated link

```
@links:
{
  "foo:b":
  {
    type: "link-template",
    // "href" is now the URL template
    "href": "http://.../issues-query?text={text}&severity={severity}&project={pid}",
    "title": "Search for issues",
    "description": "This is a simple search that does not check attachments.",
    "parameters": [
      {
        "name": "text",
        "description": "Substring search for text in title and description"
      },
      {
        "name": "severity",
        "description": "Issue severity (exact value, 1..5)"
      },
      {
        "name": "pid",
        "description": "Project ID"
      }
    ],
  }
}
```

### JSON action

The actions have not changed much. Only things is that they now live under @links instead of @actions

```
"@links":
{
  "is:update-project": {
    "type": "json",
    "href": "...",
    "method": "POST",
    "title": "Update project details",
    "description": "...",
    "schemaUrl": "...",
    "template": {
        "Code": "SHOP",
        "Title": "Webshop",
        "Description": "All issues related to the webshop."
    }
}
```

**Comment by JornWildt** [comment]
The version 2 specification will combine all links, link templates and actions into a single object. Right now the name is "@navigation" but I am looking for something better.

**Comment by kijanawoodard** [comment]
How about @transitions?

**Comment by xogeny** [comment]
"@requests"?  The point is that if you consider HTTP, what these translate into are different ways for formulating a request to the server.  The point is you are going beyond a link (which simply identifies a resource) and elaborating more on the method and potentially the payload.  That's a request.

**Comment by JornWildt** [comment]
Version 2 is now official - and uses `@controls` for all hypermedia elements together.
