### ISSUE TITLE
Resolving relative URLs

### ISSUE THREAD

**Issue by JornWildt** [JornWildt/Mason#12]
How should a client resolve relative URLs in links and actions?

- Relative to the URL from which the resource was requested?

- Relative to the innermost parent "self" link?

- Should they be forbidden (or at least discouraged - which is what the version 2 spec says)?

**Comment by xogeny** [comment]
The client should absolutely resolve relative URLs and absolute path URLs.  I'm always surprised that this is not considered a best practice in APIs.  There is a very good reason to have relative URLs and absolute path URLs and there are RFCs that define how they should be resolved.  So there is no ambiguity except to specify a base URL.  I would say relative to the requested resource.  Although it would be nice to have some kind of meta data (as with HTML) to specify/override this.

**Comment by JornWildt** [comment]
See https://groups.google.com/forum/#!topic/hal-discuss/t1xld7fsYyM for a discussion in the HAL forum.
