### ISSUE TITLE
request: list implementations in README.md

### ISSUE THREAD

**Issue by mooreniemi** [JornWildt/Mason#15]
One thing I love about JSON API is: http://jsonapi.org/implementations/

Would be very helpful to track those here for Mason.

**Comment by mooreniemi** [comment]
Looks like the only implementations are for .NET? I'm trying to get some for Ruby rolling. Mobile stuff would be huge, too.

**Comment by JornWildt** [comment]
There is a PHP server-side implementation too from phone.com. See https://github.com/JornWildt/Mason/issues/15

**Comment by JornWildt** [comment]
Added list of known implementations to README.

**Comment by mooreniemi** [comment]
Thanks @JornWildt !

**Comment by mooreniemi** [comment]
Also FWIW I have a WIP implementation for Rails going here: https://github.com/mooreniemi/amsa-mason

**Comment by JornWildt** [comment]
Thanks, added.
