### ISSUE TITLE
Issue with Mason API Explorer and JSON query parameters

### ISSUE THREAD

**Issue by BernardMarshall** [JornWildt/Mason#18]
Many thanks for the API Explorer. I have been using it extensively to test and document a Mason draft 2 based REST API. It all works well. I have found one issue with the Explorer. If you enter a URL (just type it in the URL box at the top) of the form `GET /google.com?filter=%7B%7Bfred%7D%7D` then you will get an error from UriTemplate "Failed to initialize request" with some extra spiel.

I have made up the example above, as we are trying to pass JSON via a query parameter (something like `http://some.host?filter=JSON`). For some reason Explorer seems to think the URL entered is a template rather than just a raw URL. I am not sure how easy this is to fix. I assume it is a bug as how else can you send JSON as part of a query parameter?

**Comment by JornWildt** [comment]
Fixed - but I am unable to build a new installer as the VIX project type has been de-supported in VS2015. You will have to build it for yourself.

**Comment by BernardMarshall** [comment]
Many thanks Jorn.
